Search API request query customizable, filter on user_properties for …
woosmap/woosmap-geofencing-ios-sdk pull request #39
Opened 2021-06-14 08:36 UTC by Llumbroso

…airship data

# Pull Request Template

## Types of changes

What types of changes does your code introduce to Woosmap Geofencing?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

Before you submit a pull request, please make sure you have to following:

- [X] I've read [contributing guidelines](CONTRIBUTING.md)
- [X] My code contain tests relevant for the problem I'm solving
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2021-06-14 13:37 UTC, vincentbruneauwgs requested changes

2021-06-14 13:37 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Monitor.swift
> +               let nbPage =  Int(value) ?? 0
A "min" function should do the trick instead of the if / else

2021-06-14 13:37 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Monitor.swift
> +                                    if(userPropertiesFilter.isEmpty) {
Je pense que quelque chose comme ça serait un peu plus lisible
```
      for (key, value) in userProperties {
          if(userPropertiesFilter.isEmpty || userPropertiesFilter.contains(key)) {
              propertyDictionary[key] = value
          }
      }
```

2021-06-14 13:37 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Monitor.swift
> +        print("region = " + region.identifier!)
debug log ?

2021-06-14 13:37 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Monitor.swift
> +            let jsonStructure = try? JSONDecoder().decode(JSONAny.self, from:  poi.jsonData ?? Data.init())
Tout cette fonction devrait peut-être être une methode du POIs (afin d'améliorer la lisibilité)

2021-06-14 15:28 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Monitor.swift
> +               let nbPage =  Int(value) ?? 0
Renomer nbPage en storesByPage serait plus clair

2021-06-14 15:38 UTC, vincentbruneauwgs commented
La taille des radius doit supporter les integer

il faut retirer du delegate
```
        WoosmapGeofencing.shared.setFirstSearchAPIRegionRadius(radius: 100.0)
        WoosmapGeofencing.shared.setSecondSearchAPIRegionRadius(radius: 200.0)
        WoosmapGeofencing.shared.setThirdSearchAPIRegionRadius(radius: 300.0)
```

2021-06-29 13:43 UTC, Llumbroso commented
https://github.com/WebGeoServices/woosmap/issues/992

2021-06-30 13:41 UTC, Llumbroso commented
https://github.com/WebGeoServices/woosmap/issues/992

2021-07-01 09:06 UTC, vincentbruneauwgs requested changes

2021-07-01 09:06 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Business Logic/POI.swift
> +    @objc public dynamic var country_code: String?
Il manque le champ contact

2021-07-01 09:06 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Business Logic/POI.swift
> +                                    poi.address = address.joined(separator:" - ")
il serait bien que le séparateur soit une constante

2021-07-01 09:06 UTC, vincentbruneauwgs commented on WoosmapGeofencing/Sources/WoosmapGeofencing/Monitor.swift
> +        propertyDictionary["types"] = poi.types
il faudrait aussi renvoyer les autres informations

2021-07-05 13:31 UTC, vincentbruneauwgs approved these changes

2021-07-05 13:31 UTC, merged